source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

project 'SDWebImage Demo'
workspace '../SDRNWebImage'

pod 'SDRNWebImage/Core', :path => '../'
pod 'SDWebImageWebPCoder'

target 'SDWebImage iOS Demo' do
  platform :ios, '8.0'
end

target 'SDWebImage OSX Demo' do
  platform :osx, '10.10'
end

target 'SDWebImage TV Demo' do
  platform :tvos, '9.2'
end

target 'SDWebImage Watch Demo Extension' do
  platform :watchos, '2.0'
end
